# Generated by Django 4.2.4 on 2023-08-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('due', models.DateTimeField()),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('COMPLETE', 'Complete'), ('IN PROGRESS', 'In progress')], default='INCOMPLETE', max_length=15)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
